In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("train.csv")

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.shape

(891, 12)

In [7]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [8]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [10]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["Sex"].value_counts(dropna=False)

Sex
male      577
female    314
Name: count, dtype: int64

In [13]:
df["Embarked"].value_counts(dropna=False)

Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [14]:
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [15]:
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [16]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [17]:
Q1 = df["Fare"].quantile(0.25)

In [18]:
Q3= df["Fare"].quantile(0.75)

In [19]:
IQR = Q3-Q1

In [20]:
lower_bound = Q1 - 1.5*IQR

In [21]:
upper_bound = Q3 + 1.5*IQR

In [22]:
fare_outliers = df [
    (df["Fare"] < 0) |
    (df["Fare"] > upper_bound)
]

In [23]:
fare_outliers

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,NaN,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
846,847,0,3,"Sage, Mr. Douglas Bullen",male,NaN,8,2,CA. 2343,69.5500,NaN,S
849,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,NaN,1,0,17453,89.1042,C92,C
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

In [24]:
fare_outliers.shape[0]

116

In [25]:
df[df["Age"] < 0]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [26]:
df[df["Fare"] < 0]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [27]:
df[df["SibSp"] < 0]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [28]:
df[df["Parch"] < 0]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [29]:
df["Age"].median()

28.0

In [30]:
df["Age"].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [31]:
df["Embarked"].mode()

0    S
Name: Embarked, dtype: object

In [32]:
total_rows= df.shape[0]

In [33]:
age_missing = df["Age"].isnull().sum()

In [34]:
age_missing_percent = age_missing / total_rows * 100

In [35]:
age_missing_percent

np.float64(19.865319865319865)

In [36]:
cabin_missing = df["Cabin"].isnull().sum()
cabin_missing_percent = cabin_missing / total_rows * 100

cabin_missing_percent

np.float64(77.10437710437711)

In [37]:
embarked_missing = df["Embarked"].isnull().sum()
embarked_missing_percent = embarked_missing / total_rows * 100

embarked_missing_percent

np.float64(0.22446689113355783)

In [38]:
df_clean = df.copy()

In [39]:
age_median = df["Age"].median()

In [40]:
age_median

28.0

In [41]:
df_clean["Age"] = df_clean["Age"].fillna(age_median)

In [42]:
embarked_mode = df["Embarked"].mode()[0]

In [43]:
df_clean["Embarked"] = df_clean["Embarked"].fillna(embarked_mode)

In [44]:
df_clean = df_clean.drop(columns=["Cabin"])

In [45]:
df_clean.shape

(891, 11)

In [46]:
df_clean.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [47]:
df_clean.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [48]:
df_clean.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [49]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [50]:
df_clean.to_csv("titanic_dataset.csv", index=False)

In [51]:
df_clean.to_parquet("Titanic_dataset.parquet", index=False)

In [52]:
import os

In [53]:
os.path.exists("titanic_clean.csv")

False

In [54]:
os.path.exists("titanic_dataset.csv")

True

In [55]:
os.path.exists("Titanic_dataset.parquet")

True

In [56]:
df_csv=pd.read_csv("titanic_dataset.csv")

In [57]:
df_parquet=pd.read_parquet("Titanic_dataset.parquet")

In [58]:
df_csv.shape
df_parquet.shape

(891, 11)

In [59]:
csv_size = os.path.getsize("titanic_dataset.csv")
parquet_size = os.path.getsize("Titanic_dataset.parquet")

In [60]:
csv_size_kb = csv_size / 1024
parquet_size_kb = parquet_size / 1024

csv_size_kb, parquet_size_kb

(59.6513671875, 38.9033203125)

In [61]:
import time

In [62]:
start = time.perf_counter()
df_clean.to_csv("titanic_clean.csv", index=False)
end = time.perf_counter()
csv_time = end - start
csv_time

0.008955867999986822

In [63]:
start = time.perf_counter()
df_clean.to_parquet("titanic_clean.parquet", index=False)
end = time.perf_counter()
parquet_time = end - start
parquet_time

0.0065379489999486395

In [64]:
start = time.perf_counter()
df_csv = pd.read_csv("titanic_clean.csv")
end = time.perf_counter()
csv_read_time = end - start
csv_read_time

0.009914695000020401

In [65]:
start = time.perf_counter()
df_parquet = pd.read_parquet("titanic_clean.parquet")
end = time.perf_counter()
parquet_read_time = end - start
parquet_read_time

0.007939079999971455

In [66]:
df_clean.shape

(891, 11)

In [67]:
df_parquet.shape

(891, 11)

In [68]:
df_csv.shape

(891, 11)