In [1]:
import numpy as np
import pandas as pd

In [2]:
# task 1

In [ ]:
arr = np.array([
    [10, 20, 30, 40],[10,20,30]
    [50, 60, 70, 80],[10,20,30]
    [90, 100, 110, 120],[10,20,30]
])
arr

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [4]:
arr.shape

(3, 4)

In [5]:
arr.ndim

2

In [6]:
arr.size

12

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr[1, 1]

np.int64(60)

In [9]:
arr[0, 2]

np.int64(30)

In [10]:
arr[0]

array([10, 20, 30, 40])

In [11]:
arr[:, 0]

array([10, 50, 90])

In [12]:
arr[0:2 , 1:3]

array([[20, 30],
       [60, 70]])

In [13]:
arr.mean()

np.float64(65.0)

In [14]:
arr.sum()

np.int64(780)

In [15]:
arr.min()

np.int64(10)

In [16]:
arr.max()

np.int64(120)

In [17]:
arr.std()

np.float64(34.52052529534663)

In [18]:
arr.mean(axis=0)

array([50., 60., 70., 80.])

In [19]:
arr.mean(axis=1)

array([ 25.,  65., 105.])

In [20]:
arr + 10

array([[ 20,  30,  40,  50],
       [ 60,  70,  80,  90],
       [100, 110, 120, 130]])

In [21]:
arr * 2

array([[ 20,  40,  60,  80],
       [100, 120, 140, 160],
       [180, 200, 220, 240]])

In [22]:
arr ** 2

array([[  100,   400,   900,  1600],
       [ 2500,  3600,  4900,  6400],
       [ 8100, 10000, 12100, 14400]])

In [23]:
#Task2

In [24]:
df = pd.read_csv("train.csv")

In [25]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [26]:
df.shape

(891, 12)

In [27]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [28]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [30]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [31]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [32]:
df.describe(include="object")

                       Name   Sex  Ticket Cabin Embarked
count                   891   891     891   204      889
unique                  891     2     681   147        3
top     Dooley, Mr. Patrick  male  347082    G6        S
freq                      1   577       7     4      644

In [33]:
df["Sex"].unique()

array(['male', 'female'], dtype=object)

In [34]:
df["Embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [35]:
df["Pclass"].unique()

array([3, 1, 2])

In [36]:
df.loc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [37]:
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [38]:
df.loc[0:4, ["Name","Sex","Age"]]

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [39]:
df.iloc[0:5,3:6
        ]

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [40]:
df.loc[0, "Name"]

'Braund, Mr. Owen Harris'

In [41]:
df.iloc[0,3]

'Braund, Mr. Owen Harris'

In [42]:
df.loc[0:9, ["Name", "Pclass", "Fare"]]

                                                Name  Pclass     Fare
0                            Braund, Mr. Owen Harris       3   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1  71.2833
2                             Heikkinen, Miss. Laina       3   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1  53.1000
4                           Allen, Mr. William Henry       3   8.0500
5                                   Moran, Mr. James       3   8.4583
6                            McCarthy, Mr. Timothy J       1  51.8625
7                     Palsson, Master. Gosta Leonard       3  21.0750
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)       3  11.1333
9                Nasser, Mrs. Nicholas (Adele Achem)       2  30.0708

In [43]:
df.iloc[0:10, [3, 2, 9]]

                                                Name  Pclass     Fare
0                            Braund, Mr. Owen Harris       3   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1  71.2833
2                             Heikkinen, Miss. Laina       3   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1  53.1000
4                           Allen, Mr. William Henry       3   8.0500
5                                   Moran, Mr. James       3   8.4583
6                            McCarthy, Mr. Timothy J       1  51.8625
7                     Palsson, Master. Gosta Leonard       3  21.0750
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)       3  11.1333
9                Nasser, Mrs. Nicholas (Adele Achem)       2  30.0708

In [44]:
df.loc[20:25, ["Survived", "Sex", "Age"]]

    Survived     Sex   Age
20         0    male  35.0
21         1    male  34.0
22         1  female  15.0
23         1    male  28.0
24         0  female   8.0
25         1  female  38.0

In [45]:
df.iloc[20:26, [1, 4, 5]]

    Survived     Sex   Age
20         0    male  35.0
21         1    male  34.0
22         1  female  15.0
23         1    male  28.0
24         0  female   8.0
25         1  female  38.0

In [46]:
older_60 = df[df["Age"] > 60]

older_60[["Name", "Age", "Sex", "Pclass"]]

                                          Name   Age     Sex  Pclass
33                       Wheadon, Mr. Edward H  66.0    male       2
54              Ostby, Mr. Engelhart Cornelius  65.0    male       1
96                   Goldschmidt, Mr. George B  71.0    male       1
116                       Connors, Mr. Patrick  70.5    male       3
170                  Van der hoef, Mr. Wyckoff  61.0    male       1
252                  Stead, Mr. William Thomas  62.0    male       1
275          Andrews, Miss. Kornelia Theodosia  63.0  female       1
280                           Duane, Mr. Frank  65.0    male       3
326                  Nysveen, Mr. Johan Hansen  61.0    male       3
438                          Fortune, Mr. Mark  64.0    male       1
456                  Millet, Mr. Francis Davis  65.0    male       1
483                     Turkula, Mrs. (Hedwig)  63.0  female       3
493                    Artagaveytia, Mr. Ramon  71.0    male       1
545               Nicholson, Mr. Arthur Ernest  64.0    male       1
555                         Wright, Mr. George  62.0    male       1
570                         Harris, Mr. George  62.0    male       2
625                      Sutton, Mr. Frederick  61.0    male       1
630       Barkworth, Mr. Algernon Henry Wilson  80.0    male       1
672                Mitchell, Mr. Henry Michael  70.0    male       2
745               Crosby, Capt. Edward Gifford  70.0    male       1
829  Stone, Mrs. George Nelson (Martha Evelyn)  62.0  female       1
851                        Svensson, Mr. Johan  74.0    male       3

In [47]:
female_passengers = df[df["Sex"] == "female"]
female_passengers[["Name","Sex","Age","Survived"]]

                                                  Name     Sex   Age  Survived
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0         1
2                               Heikkinen, Miss. Laina  female  26.0         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0         1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0         1
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0         1
..                                                 ...     ...   ...       ...
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0         1
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0         0
885               Rice, Mrs. William (Margaret Norton)  female  39.0         0
887                       Graham, Miss. Margaret Edith  female  19.0         1
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN         0

[314 rows x 4 columns]

In [48]:
first_class_female_survivors = df[
    (df["Sex"] == "female") &
    (df["Pclass"] == 1) &
    (df["Survived"] == 1)
]

first_class_female_survivors[
    ["Name", "Sex", "Age", "Pclass", "Survived"]
]

,Name,Sex,Age,Pclass,Survived
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,1
11,"Bonnell, Miss. Elizabeth",female,58.0,1,1
31,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,1
52,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,1
...,...,...,...,...,...
856,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1
862,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,1,1
871,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1
879,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,1,1
887,"Graham, Miss. Margaret Edith",female,19.0,1,1

In [49]:
average_fare = df["Fare"].mean()

average_fare

np.float64(32.204207968574636)

In [50]:
above_average_fare = df[df["Fare"] > average_fare]

above_average_fare[
    ["Name", "Pclass", "Fare", "Survived"]
]

,Name,Pclass,Fare,Survived
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,71.2833,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,53.1000,1
6,"McCarthy, Mr. Timothy J",1,51.8625,0
23,"Sloper, Mr. William Thompson",1,35.5000,1
27,"Fortune, Mr. Charles Alexander",1,263.0000,0
...,...,...,...,...
856,"Wick, Mrs. George Dennick (Mary Hitchcock)",1,164.8667,1
863,"Sage, Miss. Dorothy Edith ""Dolly""",3,69.5500,0
867,"Roebling, Mr. Washington Augustus II",1,50.4958,0
871,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",1,52.5542,1
879,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",1,83.1583,1

In [51]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [52]:
df.duplicated().sum()

np.int64(0)

In [53]:
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [54]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [55]:
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [56]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [57]:
df[["Age", "Fare", "SibSp", "Parch"]].describe()

              Age        Fare       SibSp       Parch
count  714.000000  891.000000  891.000000  891.000000
mean    29.699118   32.204208    0.523008    0.381594
std     14.526497   49.693429    1.102743    0.806057
min      0.420000    0.000000    0.000000    0.000000
25%     20.125000    7.910400    0.000000    0.000000
50%     28.000000   14.454200    0.000000    0.000000
75%     38.000000   31.000000    1.000000    0.000000
max     80.000000  512.329200    8.000000    6.000000

In [58]:
df["Age"].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [59]:
df["Fare"].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [60]:
df[["Age", "Fare", "SibSp", "Parch"]].corr()

            Age      Fare     SibSp     Parch
Age    1.000000  0.096067 -0.308247 -0.189119
Fare   0.096067  1.000000  0.159651  0.216225
SibSp -0.308247  0.159651  1.000000  0.414838
Parch -0.189119  0.216225  0.414838  1.000000

In [61]:
df[["Age", "Fare"]].corr()

           Age      Fare
Age   1.000000  0.096067
Fare  0.096067  1.000000

In [62]:
df["Age"].corr(df["Fare"])

np.float64(0.0960666917690389)